# syntax=docker/dockerfile:1.7
FROM soulter/astrbot:v4.26.7

USER root
WORKDIR /opt/anime-qqbot

COPY pyproject.toml README.md NOTICE ./
COPY src ./src
RUN python -m pip install --no-cache-dir .

COPY astrbot_plugin_anime_tracking /AstrBot/data/plugins/astrbot_plugin_anime_tracking

RUN python -c "import anime_qqbot" \
    && python -c "import sys; sys.path.insert(0, '/AstrBot/data/plugins'); import astrbot_plugin_anime_tracking.main"

WORKDIR /AstrBot
